language: python
python:
#  - "3.3"
  - "2.7"
  #- "2.6" #Doesn't have 'unittest discover'
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install mock
# command to run tests, e.g. python setup.py test
script:
- cd plugin
- python -m unittest discover
env: ANDROID_HOME=TEST_ANDROID_HOME
